---
- name: ansible_info
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: yes
  become: no

  tasks:

    - debug:
        var: ansible_python

    - debug:
        var: ansible_version

    - shell: |
        which ansible
        ansible --version

    - shell: |
        ansible-galaxy collection list
      register: c

    - debug:
        msg: "{{ c.stdout_lines | join('\n') }}"
