---
- name: ansible_info
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: yes
  become: no

  tasks:
    - name: ansible_python
      ansible.builtin.debug:
        var: ansible_python

    - name: ansible_version
      ansible.builtin.debug:
        var: ansible_version

    - name: ansible shell things
      ansible.builtin.shell: |
        which ansible
        ansible --version
        ansible-galaxy collection list
