---
- name: dump_vars
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: dump foo1
      ansible.builtin.debug:
        var: foo1

    - name: dump foo2
      ansible.builtin.debug:
        var: foo2

    - name: dump foo3
      ansible.builtin.debug:
        var: foo3

    - name: dump foo4
      ansible.builtin.debug:
        var: foo4

    - name: dump vars
      ansible.builtin.debug:
        var: vars

    - name: debug vars
      ansible.builtin.pause:
        seconds: 0
        prompt: |
          foo1: {{ foo1 | default('undefined', true) }}
          foo2: {{ foo2 | default('undefined', true) }}
          foo3: {{ foo3 | default('undefined', true) }}
          foo4: {{ foo4 | default('undefined', true) }}
