---
- name: fail
  hosts: "{{ ansible_limit | default('localhost', true) }},!failed"
  connection: "{{ 'local' if (ansible_limit | default('localhost', true) == 'localhost') else 'ssh' }}"
  gather_facts: false
  become: false
  tasks:

    - block:

        - name: fail
          ansible.builtin.fail:
          when: 2 | random == 0

      rescue:

        - name: add_host
          ansible.builtin.add_host:
            name: "{{ inventory_hostname }}"
            groups: failed

    - name: hello
      ansible.builtin.debug:
        msg: hello
