---
- name: Fixer
  hosts: all
  gather_facts: true
  become: false
  tasks:
    - name: Random
      when: 5 | random == 1
      block:
        - name: Ensure /etc/ansible/facts.d/custom.fact
          ansible.builtin.copy:
            dest: /etc/ansible/facts.d/custom.fact
            owner: root
            group: root
            mode: "0644"
            content: |
              {"done": true}
          register: custom_fact

        - name: Re-gather facts
          when: custom_fact is changed
          ansible.builtin.setup:
