- name: Hello World Sample
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - debug:
        msg: |
          {{ ansible_version.full }}
          {{ settings.collections_enabled }}
