---
- name: Job1
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    slack_channel: "#bots"
  tasks:
    - name: Slack
      community.general.slack:
        channel: "{{ slack_channel }}"
        token: "{{ slack_bot_token }}"
        msg: "Job1"
      register: slack_response

    - name: Stats
      ansible.builtin.set_stats:
        data:
          slack_response: "{{ slack_response }}"
