---
- name: Job3
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Slack
      when: slack_response.ts is defined and slack_response.channel is defined
      community.general.slack:
        token: "{{ slack_bot_token }}"
        channel: "{{ slack_response.channel }}"
        message_id: "{{ slack_response.ts }}"
        msg: "Job3"
