---
- name: Local facts
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Ensure /etc/ansible/facts.d
      ansible.builtin.file:
        state: directory
        path: /etc/ansible/facts.d
        owner: root
        group: root
        mode: "0755"

    - name: Ensure /etc/ansible/facts.d/custom.fact
      ansible.builtin.copy:
        dest: /etc/ansible/facts.d/custom.fact
        owner: root
        group: root
        mode: "0644"
        content: |
          {"done": "{{2 | random}}"}
      register: custom_fact

    - name: Re-gather facts
      when: custom_fact is changed
      ansible.builtin.setup:
