---
- name: long_running
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: shell
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          for i in $(seq 10); do
            date
            sleep 3
          done

    - name: ping
      ansible.builtin.ping:

    - name: prompt
      ansible.builtin.pause:
        seconds: 10
        prompt: |
          hello world

    - name: ping
      ansible.builtin.ping:
