---
- name: ping
  hosts: "{{ ansible_limit | default('localhost', true) }}"
  connection: "{{ 'local' if ansible_limit | default('localhost', true) == 'localhost' else 'ssh' }}"
  gather_facts: false
  become: false

  tasks:

    - name: ping
      ansible.builtin.ping:
