---
- name: say
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: yes
  become: no

  tasks:

    - name: Makes a computer to speak
      community.general.say:
        msg: '{{ inventory_hostname }} is all done'
        voice: Zarvox
      delegate_to: localhost
