---
- name: secret
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: env
      ansible.builtin.shell:
        cmd: env | sort

    - name: debug
      ansible.builtin.debug:
        msg: |
          {{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/foo:password') }}
      environment:
        ANSIBLE_HASHI_VAULT_ADDR: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
        ANSIBLE_HASHI_VAULT_AUTH_METHOD: "{{ lookup('ansible.builtin.env', 'VAULT_AUTH_METHOD') }}"
        ANSIBLE_HASHI_VAULT_ROLE_ID: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID') }}"
        ANSIBLE_HASHI_VAULT_SECRET_ID: "{{ lookup('ansible.builtin.env', 'VAULT_SECRET_ID') }}"
