---
- name: secret
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: debug
      ansible.builtin.debug:
        msg: |
          {{ lookup('community.general.hashi_vault', 'secret=secret/foo:password') }}
