---
- name: secret
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: debug
      ansible.builtin.debug:
        msg: |
          password: {{ lookup('ansible.builtin.env', 'PASSWORD') }}
