---
- name: secret
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: env
      ansible.builtin.shell:
        cmd: env | sort

    - name: debug
      ansible.builtin.debug:
        msg: |
          password: {{ password }}

    # - name: debug
    #   ansible.builtin.debug:
    #     msg: |
    #       {{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/test:password') }}
    #   ignore_errors: true

    # - name: debug
    #   ansible.builtin.debug:
    #     msg: |
    #       {{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/test:password') }}
    #   vars:
    #     ansible_hashi_vault_role_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID') }}"
    #     ansible_hashi_vault_secret_id: "{{ lookup('ansible.builtin.env', 'VAULT_SECRET_ID') }}"
    #   ignore_errors: true
