---
- name: set_stats
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: set a stat
      ansible.builtin.set_stats:
        data:
          foo1: bar1

    - name: set a stat (aggregate)
      ansible.builtin.set_stats:
        data:
          foo2: bar2
        aggregate: true

    - name: set a stat (aggregate and per_host)
      ansible.builtin.set_stats:
        data:
          foo3: bar3
        aggregate: true
        per_host: true
