---
- name: sleep + fail randomly
  hosts: "{{ ansible_limit | default(omit) }}"
  connection: "{{ 'local' if ansible_limit == 'localhost' else 'ssh' }}"
  gather_facts: false
  become: false
  tasks:

    - name: Sleep for a minute
      ansible.builtin.pause:
        minutes: 1

    - name: Fail randomly
      ansible.builtin.fail:
        msg: failing
      when: 2 | random == 1
