---
- name: sleep_rand_fail
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Sleep for a minute
      ansible.builtin.pause:
        minutes: 1

    - name: Fail randomly
      ansible.builtin.fail:
        msg: failing
      when: 5 | random == 1
