---
- name: sleep + fail randomly
  hosts: "{{ ansible_limit | default(omit) }}"
  connection: "{{ 'local' if ansible_limit = 'localhost else 'ssh' }}"
  gather_facts: yes
  become: no
  tasks:

    - name: Sleep for 5 minutes
      ansible.builtin.pause:
        minutes: 5

    - name: Fail randomly
      ansible.builtin.fail:
      when: random | 3 == 1
