---
- name: sleep
  hosts: "{{ ansible_limit | default('localhost', True) }}"
  connection: "{{ 'local' if (ansible_limit | default('localhost', True) == 'localhost') else 'ssh' }}"
  gather_facts: false
  become: false

  tasks:

    - name: Sleep
      pause:
        minutes: "{{ sleep_minutes | default(1, True) }}"
