---
- name: statsd
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: yes
  become: no

  tasks:
    - name: Sent metric to statsd
      shell: |
        echo "{{ metric }}" >/dev/tcp/{{ endpoint }}/{{ port }}

    - name: Send metric to statsd (the right way :D)
      community.general.statsd:
        metric_type: counter
        metric: foo
        value: 1
