---
- name: statsd
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: yes
  become: no

  tasks:
    - name: Sent metric to statsd
      shell: |
        echo "{{ metric }}" >/dev/tcp/{{ endpoint }}/{{ port }}
