---
- name: test1
  hosts: "{{ (['!localhost'] + passed_hosts|default([],true)) | join(':') }}"
  connection: "{{ 'local' if ansible_limit | default('localhost', true) == 'localhost' else 'ssh' }}"
  gather_facts: false
  become: false
  max_fail_percentage: 100

  tasks:

    - name: block
      block:

        - name: fail half the time
          ansible.builtin.fail:
          when: 2 | random == 1

      rescue:

        - name: stats
          ansible.builtin.set_stats:
            aggregate: true
            per_host: false
            data:
              failed_hosts: "{{ failed_hosts|default([],true) + [inventory_hostname] }}"
              passed_hosts: "{{ passed_hosts|default([],true) | difference([inventory_hostname]) }}"

        - name: fail
          ansible.builtin.fail:

    - name: stats
      ansible.builtin.set_stats:
        aggregate: true
        per_host: false
        data:
          passed_hosts: "{{ passed_hosts|default([],true) + [inventory_hostname] }}"
          failed_hosts: "{{ failed_hosts|default([],true) | difference([inventory_hostname]) }}"
