- name: Get the current epoch time
  ansible.builtin.command: date +%s
  register: epoch

- name: Set a fact for current epoch time
  ansible.builtin.set_fact:
    epoch: "{{ epoch.stdout | trim }}"

- name: Send Job Template gauge
  community.general.statsd:
    state: present
    host: "{{ statsd_host }}"
    port: "{{ statsd_port }}"
    protocol: "{{ statsd_protocol }}"
    metric_type: gauge
    metric: awx_job_template.development.dev.test_statsd.attempt
    value: "{{ epoch }}"

- name: Fetch StatsD metrics
  ansible.builtin.uri:
    url: http://{{ statsd_host }}:{{ metrics_port }}/metrics
    return_content: true
  register: statsd_result

- name: Find it
  ansible.builtin.set_fact:
    matches: "{{ statsd_result.content | regex_findall('awx_job_template_gauge_attempt{environment=\"development\",job_template=\"test_statsd\",metric_type=\"gauge\",train=\"dev\"} (.+)', multiline=True) }}"

- name: Check it
  ansible.builtin.assert:
    that:
      - matches is defined
      - matches | length == 1

- name: Store it
  ansible.builtin.set_fact:
    gauge1: "{{ matches[0] | int }}"

- name: Check that it is as expected
  ansible.builtin.assert:
    that:
      - gauge1 == epoch
